### ISSUE TITLE
NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x000056542dcceb88>

### ISSUE THREAD

**Issue by ryderkun** [Loriowar/redmine_issues_tree#114]
redmine-3.4.6/plugins/redmine_issues_tree# bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace
(in /data/redmine/redmine-3.4.6)
rake aborted!
NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x000056542dcceb88>
/var/lib/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/railtie/configuration.rb:96:in `method_missing'
/data/redmine/redmine-3.4.6/config/application.rb:20:in `<class:Application>'
/data/redmine/redmine-3.4.6/config/application.rb:8:in `<module:RedmineApp>'
/data/redmine/redmine-3.4.6/config/application.rb:7:in `<top (required)>'
/data/redmine/redmine-3.4.6/Rakefile:5:in `require'
/data/redmine/redmine-3.4.6/Rakefile:5:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:29:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:29:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:703:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:104:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:103:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:82:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
/usr/bin/rake:27:in `<main>'

**Comment by Tab10id** [comment]
Run migrations from redmine directory, not from plugin directory.
