### ISSUE TITLE
500 Internal Server Error after click issues tree icon

### ISSUE THREAD

**Issue by ZurekProspeo** [Loriowar/redmine_issues_tree#116]
Environment:
  Redmine version                3.4.8.stable
  Ruby version                   2.6.0-p0 (2018-12-25) [x86_64-linux]
  Rails version                  4.2.11
  Environment                    production
  Database adapter               PostgreSQL

Centos 7 + nginx
```
Started GET "/projects/agc-ppk-wdrozenie-i-szkolenie/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=last_updated_by&c%5B%5D=tags_relations&c%5B%5D=spent_hours&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=agc-ppk-wdrozenie-i-szkolenie&set_filter=1&sort=id%3Adesc&t%5B%5D=spent_hours&t%5B%5D=" for 192.168.2.11 at 2020-10-21 14:02:38 +0200
Processing by IssuesTreesController#tree_index as HTML
  Parameters: {"c"=>["tracker", "status", "priority", "subject", "assigned_to", "last_updated_by", "tags_relations", "spent_hours"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"agc-ppk-wdrozenie-i-szkolenie", "set_filter"=>"1", "sort"=>"id:desc", "t"=>["spent_hours", ""]}
  Current user: MZU (id=26)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_plain_view.html.haml (3.3ms)
  Rendered queries/_filters.html.erb (19.4ms)
  Rendered queries/_columns.html.erb (3.5ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_query_form.html.erb (29.4ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.erb (14.5ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.erb (29.3ms)
  Rendered plugins/redmine_agile/app/views/agile_boards/_issues_sidebar.html.erb (0.1ms)
  Rendered plugins/redmine_agile/app/views/agile_charts/_agile_charts.html.erb (0.1ms)
  Rendered plugins/redmine_contacts_helpdesk/app/views/issues/_helpdesk_reports.html.erb (1.9ms)
  Rendered plugins/redmine_contacts_helpdesk/app/views/issues/_helpdesk_customer_profile.html.erb (0.1ms)
  Rendered plugins/redmine_contacts/app/views/contacts_issues/_contacts.html.erb (1.8ms)
  Rendered plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb (1441.6ms)
  Rendered issues/_sidebar.html.erb (1456.9ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb within layouts/base (1552.7ms)
Completed 500 Internal Server Error in 1669ms (ActiveRecord: 38.8ms)

ActionView::Template::Error (undefined local variable or method `sidebar_tags' for #<#<Class:0x00007fa2eb99c740>:0x00007fa2eb9a0ea8>
Did you mean?  sidebar_agile_queries):
    1: <% unless sidebar_tags.empty? -%>
    2: <div class="sidebar-tags">
    3:   <h3><%= l(:tags) %></h3>
    4:   <%= render_sidebar_tags %>
  plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb:1:in `_plugins_redmineup_tags_app_views_issues__tags_sidebar_html_erb__3004561133105215046_70168854038440'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_sidebar.html.erb:15:in `_app_views_issues__sidebar_html_erb__278557048634901827_70168853718180'
  plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb:48:in `block in _plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_erb__3218416016828725760_70168857129200'
  plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb:47:in `_plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_erb__3218416016828725760_70168857129200'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/helpdesk_mailer/get_mail?key=oZHZOa3IOkKvfZcePkjj" for 127.0.0.1 at 2020-10-21 14:05:03 +0200
Processing by HelpdeskMailerController#get_mail as */*
  Parameters: {"key"=>"oZHZOa3IOkKvfZcePkjj"}
  Rendered text template (0.1ms)
Completed 200 OK in 189ms (Views: 15.4ms | ActiveRecord: 64.5ms)
Started POST "/projects/agc-ppk-wdrozenie-i-szkolenie/issues_trees/redirect_with_params" for 192.168.2.11 at 2020-10-21 14:05:32 +0200
Processing by IssuesTreesController#redirect_with_params as JSON
  Parameters: {"utf8"=>"✓", "set_filter"=>"1", "sort"=>"id:desc", "f"=>["status_id", ""], "op"=>{"status_id"=>"o"}, "c"=>["tracker", "status", "priority", "subject", "assigned_to", "last_updated_by", "tags_relations", "spent_hours"], "group_by"=>"", "t"=>["spent_hours", ""], "project_id"=>"agc-ppk-wdrozenie-i-szkolenie"}
  Current user: MZU (id=26)
Completed 200 OK in 96ms (Views: 1.5ms | ActiveRecord: 20.5ms)
Started GET "/projects/agc-ppk-wdrozenie-i-szkolenie/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=last_updated_by&c%5B%5D=tags_relations&c%5B%5D=spent_hours&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=agc-ppk-wdrozenie-i-szkolenie&set_filter=1&sort=id%3Adesc&t%5B%5D=spent_hours&t%5B%5D=" for 192.168.2.11 at 2020-10-21 14:05:32 +0200
Processing by IssuesTreesController#tree_index as HTML
  Parameters: {"c"=>["tracker", "status", "priority", "subject", "assigned_to", "last_updated_by", "tags_relations", "spent_hours"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"agc-ppk-wdrozenie-i-szkolenie", "set_filter"=>"1", "sort"=>"id:desc", "t"=>["spent_hours", ""]}
  Current user: MZU (id=26)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_plain_view.html.haml (2.0ms)
  Rendered queries/_filters.html.erb (26.1ms)
  Rendered queries/_columns.html.erb (3.9ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_query_form.html.erb (35.1ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.erb (21.7ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.erb (31.2ms)
  Rendered plugins/redmine_agile/app/views/agile_boards/_issues_sidebar.html.erb (0.1ms)
  Rendered plugins/redmine_agile/app/views/agile_charts/_agile_charts.html.erb (0.1ms)
  Rendered plugins/redmine_contacts_helpdesk/app/views/issues/_helpdesk_reports.html.erb (2.5ms)
  Rendered plugins/redmine_contacts_helpdesk/app/views/issues/_helpdesk_customer_profile.html.erb (0.1ms)
  Rendered plugins/redmine_contacts/app/views/contacts_issues/_contacts.html.erb (0.1ms)
  Rendered plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb (1821.9ms)
  Rendered issues/_sidebar.html.erb (1830.3ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb within layouts/base (1925.1ms)
Completed 500 Internal Server Error in 2089ms (ActiveRecord: 56.0ms)

ActionView::Template::Error (undefined local variable or method `sidebar_tags' for #<#<Class:0x00007fa2eb99c740>:0x00007fa2eb59cf50>
Did you mean?  sidebar_agile_queries):
    1: <% unless sidebar_tags.empty? -%>
    2: <div class="sidebar-tags">
    3:   <h3><%= l(:tags) %></h3>
    4:   <%= render_sidebar_tags %>
  plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb:1:in `_plugins_redmineup_tags_app_views_issues__tags_sidebar_html_erb__3004561133105215046_70168854038440'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_sidebar.html.erb:15:in `_app_views_issues__sidebar_html_erb__278557048634901827_70168853718180'
  plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb:48:in `block in _plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_erb__3218416016828725760_70168857129200'
  plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb:47:in `_plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_erb__3218416016828725760_70168857129200'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by Loriowar** [comment]
Look like you using `redmineup_tags` plugin. For now, `redmine_issues_tree` not compatible with that plugin. Here is the initial issue: https://github.com/Loriowar/redmine_issues_tree/issues/111. You may help with this: implement the support of tags plugin and create a PR. Or may wait until Redmine merged that plugin into core and then I'll implement support of it.

**Comment by pkoevesdi** [comment]
I can confirm, had the same issue until I removed `redmineup_tags`.
