### ISSUE TITLE
Unable to install in docker environment for 5.0

### ISSUE THREAD

**Issue by bertalanimre** [Loriowar/redmine_issues_tree#130]
Hey there! I've tried to install the plugin in a docker environment, however, I came across some issue. Here is what I did:
* Cloned the 5.0.x branch into my volumes/plugin folder
* Tried to restart the redmine container
* Error....

My docker compose file is as following:
```
version: '3.6'
services:
  redmine:
    image: redmine:5.0.3
    ports:
      - '3000:$REDMINE_PORT'
    environment:
      REDMINE_DB_MYSQL: $HOSTIP
      REDMINE_DB_PORT: $DB_PORT
      REDMINE_DB_USERNAME: $DB_USERNAME
      REDMINE_DB_PASSWORD: $DB_PASSWORD
      REDMINE_DB_DATABASE: $DB_DATABASE
#      REDMINE_NO_DB_MIGRATE: true
#      REDMINE_PLUGINS_MIGRATE: true
    volumes:
      - '../volumes/files:/usr/src/redmine/files'
      - '../volumes/plugins:/usr/src/redmine/plugins'
      - '../volumes/themes:/usr/src/redmine/public/themes'
      - '../volumes/configuration.yml:/usr/src/redmine/config/configuration.yml'
```

The process of installing the plugin ended like this:
```
web@redmine:/opt/apps/redmine-docker$ docker compose down
[+] Running 2/2
 ⠿ Container redmine-docker-redmine-1  Removed                                                                                                                                                              0.8s
 ⠿ Network redmine-docker_default      Removed                                                                                                                                                              0.1s
web@redmine:/opt/apps/redmine-docker$ docker compose up
[+] Running 2/2
 ⠿ Network redmine-docker_default      Created                                                                                                                                                              0.1s
 ⠿ Container redmine-docker-redmine-1  Created                                                                                                                                                              0.1s
Attaching to redmine-docker-redmine-1
redmine-docker-redmine-1  | Your Gemfile lists the gem puma (>= 0) more than once.
redmine-docker-redmine-1  | You should probably keep only one of them.
redmine-docker-redmine-1  | Remove any duplicate entries and specify the gem only once.
redmine-docker-redmine-1  | While it's not a problem now, it could cause errors if you change the version of one of them later.
redmine-docker-redmine-1  | Bundler can't satisfy your Gemfile's dependencies.
redmine-docker-redmine-1  | Install missing gems with `bundle install`.
redmine-docker-redmine-1  | Your Gemfile lists the gem puma (>= 0) more than once.
redmine-docker-redmine-1  | You should probably keep only one of them.
redmine-docker-redmine-1  | Remove any duplicate entries and specify the gem only once.
redmine-docker-redmine-1  | While it's not a problem now, it could cause errors if you change the version of one of them later.
redmine-docker-redmine-1  | Fetching gem metadata from https://rubygems.org/.........
redmine-docker-redmine-1  | Resolving dependencies...
redmine-docker-redmine-1  | Using rake 13.0.6
redmine-docker-redmine-1  | Using concurrent-ruby 1.1.10
redmine-docker-redmine-1  | Using minitest 5.16.3
redmine-docker-redmine-1  | Using zeitwerk 2.6.1
redmine-docker-redmine-1  | Using builder 3.2.4
redmine-docker-redmine-1  | Using erubi 1.11.0
redmine-docker-redmine-1  | Using racc 1.6.0
redmine-docker-redmine-1  | Using crass 1.0.6
redmine-docker-redmine-1  | Using rack 2.2.4
redmine-docker-redmine-1  | Using nio4r 2.5.8
redmine-docker-redmine-1  | Using websocket-extensions 0.1.5
redmine-docker-redmine-1  | Using marcel 1.0.2
redmine-docker-redmine-1  | Using mini_mime 1.1.2
redmine-docker-redmine-1  | Using method_source 1.0.0
redmine-docker-redmine-1  | Using thor 1.2.1
redmine-docker-redmine-1  | Using public_suffix 5.0.0
redmine-docker-redmine-1  | Using bundler 2.3.7
redmine-docker-redmine-1  | Using chunky_png 1.4.0
redmine-docker-redmine-1  | Using commonmarker 0.23.4
redmine-docker-redmine-1  | Using csv 3.2.5
redmine-docker-redmine-1  | Using digest 3.1.0
redmine-docker-redmine-1  | Fetching tilt 2.0.11
redmine-docker-redmine-1  | Using htmlentities 4.3.4
redmine-docker-redmine-1  | Fetching liquid 2.6.3
redmine-docker-redmine-1  | Using mini_magick 4.11.0
redmine-docker-redmine-1  | Using mysql2 0.5.4
redmine-docker-redmine-1  | Using timeout 0.3.0
redmine-docker-redmine-1  | Using strscan 3.0.4
redmine-docker-redmine-1  | Using net-ldap 0.17.1
redmine-docker-redmine-1  | Fetching temple 0.9.1
redmine-docker-redmine-1  | Using rbpdf-font 1.19.1
redmine-docker-redmine-1  | Using redcarpet 3.5.1
redmine-docker-redmine-1  | Using rubyzip 2.3.2
redmine-docker-redmine-1  | Using rexml 3.2.5
redmine-docker-redmine-1  | Using rouge 3.28.0
redmine-docker-redmine-1  | Using rqrcode_core 1.2.0
redmine-docker-redmine-1  | Using i18n 1.10.0
redmine-docker-redmine-1  | Using tzinfo 2.0.5
redmine-docker-redmine-1  | Using nokogiri 1.13.8 (x86_64-linux)
redmine-docker-redmine-1  | Using rack-test 2.0.2
redmine-docker-redmine-1  | Using rotp 6.2.0
redmine-docker-redmine-1  | Using websocket-driver 0.7.5
redmine-docker-redmine-1  | Using addressable 2.8.1
redmine-docker-redmine-1  | Using puma 5.6.5
redmine-docker-redmine-1  | Using sprockets 4.1.1
redmine-docker-redmine-1  | Using request_store 1.5.1
redmine-docker-redmine-1  | Using activesupport 6.1.7
redmine-docker-redmine-1  | Using loofah 2.19.0
redmine-docker-redmine-1  | Using mail 2.7.1
redmine-docker-redmine-1  | Using css_parser 1.12.0
redmine-docker-redmine-1  | Using net-protocol 0.1.3
redmine-docker-redmine-1  | Using rbpdf 1.20.1
redmine-docker-redmine-1  | Using rqrcode 2.1.2
redmine-docker-redmine-1  | Using sanitize 6.0.0
redmine-docker-redmine-1  | Using rails-dom-testing 2.0.3
redmine-docker-redmine-1  | Using rails-html-sanitizer 1.4.3
redmine-docker-redmine-1  | Using globalid 1.0.0
redmine-docker-redmine-1  | Using activemodel 6.1.7
redmine-docker-redmine-1  | Using html-pipeline 2.13.2
redmine-docker-redmine-1  | Using net-imap 0.2.3
redmine-docker-redmine-1  | Using net-pop 0.1.2
redmine-docker-redmine-1  | Using net-smtp 0.3.2
redmine-docker-redmine-1  | Using roadie 5.0.1
redmine-docker-redmine-1  | Using actionview 6.1.7
redmine-docker-redmine-1  | Using activejob 6.1.7
redmine-docker-redmine-1  | Using activerecord 6.1.7
redmine-docker-redmine-1  | Using deckar01-task_list 2.3.2
redmine-docker-redmine-1  | Using actionpack 6.1.7
redmine-docker-redmine-1  | Using actioncable 6.1.7
redmine-docker-redmine-1  | Using activestorage 6.1.7
redmine-docker-redmine-1  | Using actionmailer 6.1.7
redmine-docker-redmine-1  | Using railties 6.1.7
redmine-docker-redmine-1  | Using sprockets-rails 3.4.2
redmine-docker-redmine-1  | Using actionmailbox 6.1.7
redmine-docker-redmine-1  | Using actionpack-xml_parser 2.0.1
redmine-docker-redmine-1  | Using actiontext 6.1.7
redmine-docker-redmine-1  | Using roadie-rails 3.0.0
redmine-docker-redmine-1  | Using rails 6.1.7
redmine-docker-redmine-1  | Installing temple 0.9.1
redmine-docker-redmine-1  | Installing tilt 2.0.11
redmine-docker-redmine-1  | Installing liquid 2.6.3
redmine-docker-redmine-1  | Fetching redmine_crm 0.0.58
redmine-docker-redmine-1  | Fetching haml 6.0.10
redmine-docker-redmine-1  | Installing redmine_crm 0.0.58
redmine-docker-redmine-1  | Installing haml 6.0.10 with native extensions
redmine-docker-redmine-1  | Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
redmine-docker-redmine-1  |
redmine-docker-redmine-1  |     current directory: /usr/local/bundle/gems/haml-6.0.10/ext/haml
redmine-docker-redmine-1  | /usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r
redmine-docker-redmine-1  | ./siteconf20221121-23-81a7gy.rb extconf.rb
redmine-docker-redmine-1  | creating Makefile
redmine-docker-redmine-1  |
redmine-docker-redmine-1  | current directory: /usr/local/bundle/gems/haml-6.0.10/ext/haml
redmine-docker-redmine-1  | make DESTDIR\= clean
redmine-docker-redmine-1  | current directory: /usr/local/bundle/gems/haml-6.0.10/ext/haml
redmine-docker-redmine-1  | make DESTDIR\=
redmine-docker-redmine-1  | make failedNo such file or directory - make
redmine-docker-redmine-1  |
redmine-docker-redmine-1  | Gem files will remain installed in /usr/local/bundle/gems/haml-6.0.10 for
redmine-docker-redmine-1  | inspection.
redmine-docker-redmine-1  | Results logged to
redmine-docker-redmine-1  | /usr/local/bundle/extensions/x86_64-linux/3.1.0/haml-6.0.10/gem_make.out
redmine-docker-redmine-1  |
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:70:in `rescue in run'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:67:in `run'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:44:in `block in make'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:36:in `each'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:36:in `make'
redmine-docker-redmine-1  | /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:63:in `block in
redmine-docker-redmine-1  | build'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/tempfile.rb:317:in `open'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
redmine-docker-redmine-1  | /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
redmine-docker-redmine-1  | build_extensions'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
redmine-docker-redmine-1  | /usr/local/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:71:in
redmine-docker-redmine-1  | `build_extensions'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:28:in `install'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/bundler/source/rubygems.rb:204:in `install'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:54:in `install'
redmine-docker-redmine-1  | /usr/local/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:16:in
redmine-docker-redmine-1  | `install_from_spec'
redmine-docker-redmine-1  | /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in
redmine-docker-redmine-1  | `do_install'
redmine-docker-redmine-1  | /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in
redmine-docker-redmine-1  | `block in worker_pool'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/bundler/worker.rb:57:in `block in process_queue'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/bundler/worker.rb:54:in `loop'
redmine-docker-redmine-1  |   /usr/local/lib/ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
redmine-docker-redmine-1  | /usr/local/lib/ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in
redmine-docker-redmine-1  | create_threads'
redmine-docker-redmine-1  |
redmine-docker-redmine-1  | An error occurred while installing haml (6.0.10), and Bundler cannot continue.
redmine-docker-redmine-1  |
redmine-docker-redmine-1  | In Gemfile:
redmine-docker-redmine-1  |   haml-rails was resolved to 2.1.0, which depends on
redmine-docker-redmine-1  |     haml
redmine-docker-redmine-1 exited with code 5
```

I'm no expert in Ruby, so this is almost Chinese for me, but looks like the plugin is missing some package (haml) from the official redmine docker image? If so, please, somebody confirm this to me, so I can try to include it. Also, if it requires more, a complete list would be much loved.

Thanks !

**Comment by Loriowar** [comment]
Yes, `haml-rails` (which depelds from `haml` gem) is a [single required gem by the plugin](https://github.com/Loriowar/redmine_issues_tree/blob/5.0.x/Gemfile). In case of local installation for Redmine 5.0 I have follows content of `Gemfile.lock` after a success `bundle install`:
```ruby
haml (5.2.2)
  temple (>= 0.8.0)
  tilt
haml-rails (2.0.1)
  actionpack (>= 5.1)
  activesupport (>= 5.1)
  haml (>= 4.0.6, < 6.0)
  html2haml (>= 1.0.1)
  railties (>= 5.1)
html-pipeline (2.13.2)
  activesupport (>= 2)
  nokogiri (>= 1.4)
html2haml (2.2.0)
  erubis (~> 2.7.0)
  haml (>= 4.0, < 6)
  nokogiri (>= 1.6.0)
  ruby_parser (~> 3.5)
```

In your case something went wrong while installing `haml` gem. Looks like you env has no tools for building a native extension for `haml` gem (no `make` binary which is usually licated at `/usr/bin/make`). If you can add `haml` and `haml-rails` as prebuild gems into your Docker env, then all should be fine.

**Comment by bertalanimre** [comment]
Then my observation was a success :) I have an idea how to solve that tomorrow. I'll post it if it works, however, this is strange for me. How come a basic gem (I assume it is basic if your plugin requires it) is not included in the official image? Meh....

**Comment by Loriowar** [comment]
@bertalanimre most probably, because Redmine doesn't use `haml` at all. And an official image is oriented only on pure Redmine without any plugins. This make sence, becaue they can't add all possible gems into the image to support all existing plugins.

**Comment by bertalanimre** [comment]
Thanks for the help. This was the sollution:

Modify the docker-compose.yml
```
version: '3.6'
services:
  redmine:
    build: .
    ports:
      - '3000:$REDMINE_PORT'
    environment:
      REDMINE_DB_MYSQL: $HOSTIP
      REDMINE_DB_PORT: $DB_PORT
      REDMINE_DB_USERNAME: $DB_USERNAME
      REDMINE_DB_PASSWORD: $DB_PASSWORD
      REDMINE_DB_DATABASE: $DB_DATABASE
#      REDMINE_NO_DB_MIGRATE: true
#      REDMINE_PLUGINS_MIGRATE: true
    volumes:
      - '../volumes/files:/usr/src/redmine/files'
      - '../volumes/plugins:/usr/src/redmine/plugins'
      - '../volumes/themes:/usr/src/redmine/public/themes'
      - '../volumes/configuration.yml:/usr/src/redmine/config/configuration.yml'
```

Changed the `image: redmine:5.0.3` to `build: .build: .`.

Created a new file as: Dockerfile

```
FROM redmine:5.0.3

RUN apt update && apt install -y git build-essential imagemagick libmagickcore-dev libmagickwand-dev ruby-dev

RUN gem install haml
```

Then I just executed the following in order:
* docker compose down 
* docker compose build
* docker compose up -d

Everything went as smooth as butter, Thanks again 👍

**Comment by mihirnrajani** [comment]
Hi, I am facing the same issue. 
But I haven't used docker compose, can it be done without docker-compose as well?

**Comment by Loriowar** [comment]
@mihirnrajani technically, docker-compose is more friendly tool build upon docker. So, yes, you can do it without doker-compose. But, unfortunately, I'm not a specialist in docker/docker-compose. So, can't help with that tools and with its configuration.
