### ISSUE TITLE
Odd trouble with credativUK/redmine_image_clipboard_paste

### ISSUE THREAD

**Issue by walkwolf** [Loriowar/redmine_issues_tree#21]
I use bitnami redmine-3.2.0-0 on Centos6.4.
And some plugins installed.
When use the credativUK/redmine_image_clipboard_paste (https://github.com/credativUK/redmine_image_clipboard_paste) and redmine_issues_tree togater, project Wiki page come error. But use the one of above,it's no problem.
Maybe cause from `credativUK/redmine_image_clipboard_paste`.

Redmine log below.

```
Started GET "/redmine/projects/parent_1/wiki" for 192.168.20.131 at 2016-01-20 11:31:26 +0800
Processing by WikiController#show as HTML
  Parameters: {"project_id"=>"parent_1"}
  Current user: admin (id=1)
  Rendered plugins/redmine_image_clipboard_paste/app/views/wiki/edit.html.erb within layouts/base (6.2ms)
Completed 500 Internal Server Error in 26ms (ActiveRecord: 4.3ms)

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object. It must implement :to_partial_path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
  app/controllers/wiki_controller.rb:73:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Some info below

```
bash-4.1$ gem -v
2.0.14.1
bash-4.1$ bundle -v
Bundler version 1.10.4
bash-4.1$ gem list

*** LOCAL GEMS ***

actionmailer (4.2.5, 4.2.4)
actionpack (4.2.5, 4.2.4)
actionpack-action_caching (1.1.1)
actionpack-xml_parser (1.0.2)
actionview (4.2.5, 4.2.4)
activejob (4.2.5, 4.2.4)
activemodel (4.2.5, 4.2.4)
activerecord (4.2.5, 4.2.4)
activesupport (4.2.5, 4.2.4)
acts-as-taggable-on (3.5.0)
addressable (2.4.0)
akami (1.2.0)
arel (6.0.3)
atomic (1.1.14)
awesome_nested_set (3.0.3)
aws-sdk (2.1.1)
aws-sdk-core (2.1.1)
aws-sdk-resources (2.1.1)
bcrypt-ruby (3.1.1)
bigdecimal (1.2.0)
binding_of_caller (0.7.2)
bluecloth (2.2.0)
builder (3.2.2)
bundler (1.10.4)
byebug (3.5.1)
charlock_holmes (0.6.9.4)
coderay (1.1.0)
coffee-rails (4.1.0)
coffee-script (2.2.0)
coffee-script-source (1.6.2)
columnize (0.9.0)
concurrent-ruby (1.0.0)
crack (0.3.1)
css_parser (1.3.7)
daemon_controller (1.2.0)
daemons (1.1.8)
debug_inspector (0.0.2)
debugger-linecache (1.2.0)
diff-lcs (1.1.3)
erubis (2.7.0)
escape_utils (0.2.4)
eventmachine (1.0.4)
execjs (1.4.0)
faraday (0.8.4)
faraday_middleware (0.9.0)
fast_stack (0.1.0)
fast_xor (1.1.1)
fast_xs (0.8.0)
ffi (1.9.0)
gherkin (2.11.1)
github-markdown (0.5.3)
globalid (0.3.6)
gyoku (0.4.6)
haml (4.0.7)
haml-rails (0.9.0)
hashie (1.2.0)
hike (1.2.3)
hiredis (0.4.5)
hoe (3.0.6)
hoe-bundler (1.2.0)
hoe-debugging (1.0.5)
hoe-gemspec (1.0.0)
html2haml (2.0.0)
htmlentities (4.3.1)
http_parser.rb (0.5.3)
httparty (0.8.3)
httpauth (0.2.0)
i18n (0.7.0)
iconv (1.0.3)
io-console (0.4.2)
jbuilder (2.0.7)
jmespath (1.0.2)
jquery-rails (3.1.4, 3.0.4)
json (1.8.3, 1.7.7)
jwt (0.1.8)
libv8 (3.16.14.3 x86_64-linux)
loofah (2.0.3)
mail (2.6.3)
memcache-client (1.8.5)
mime-types (2.99, 2.6.2)
mini_magick (3.4)
mini_portile (0.6.0)
mini_portile2 (2.0.0)
minitest (5.8.3, 5.8.1, 4.3.2, 3.3.0)
multi_json (1.5.0, 1.3.6)
multi_xml (0.5.1)
multipart-post (1.1.5)
mysql2 (0.3.14)
net-ldap (0.12.1)
nokogiri (1.6.7, 1.6.2.1, 1.5.9)
oauth (0.4.7)
oj (2.0.11)
omniauth (1.1.4)
passenger (5.0.6)
pg (0.18.0.pre20141117110243, 0.15.1)
polyglot (0.3.3)
posix-spawn (0.3.6)
protected_attributes (1.1.3)
psych (2.0.0)
racc (1.4.8)
rack (1.6.4)
rack-openid (1.4.2)
rack-test (0.6.3)
rails (4.2.5, 4.2.4)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.2)
railties (4.2.5, 4.2.4)
rake (10.4.2, 0.9.6, 0.8.7)
rake-compiler (0.8.1)
rbpdf (1.19.0)
rbpdf-font (1.19.0)
rdiscount (1.6.8)
rdoc (4.0.0)
redcarpet (3.3.3, 3.0.0, 2.2.2)
RedCloth (4.2.9)
redis (3.0.4)
ref (1.0.2)
render_parent (0.0.7)
request_store (1.0.5)
require_patch (0.2.0, 0.1.0)
rexical (1.0.5)
rinku (1.7.3)
rmagick (2.15.4, 2.13.1)
roadie (3.1.0)
roadie-rails (1.1.0)
rspec (2.11.0)
rspec-core (2.11.1)
rspec-expectations (2.11.2)
rspec-mocks (2.11.1)
ruby-hmac (0.4.0)
ruby-openid (2.3.0)
ruby_parser (3.7.2)
rvm (1.11.3.5)
sass (3.4.14)
sass-rails (5.0.3)
sdoc (0.4.0)
sexp_processor (4.6.0)
simple_oauth (0.1.9)
slop (3.6.0)
spring (1.2.0)
sprockets (3.5.1, 3.4.0, 2.2.1)
sprockets-rails (2.3.3)
sqlite3 (1.3.10)
sqlite3-ruby (1.3.3)
subexec (0.2.2)
test-unit (2.0.0.0)
therubyracer (0.12.0)
thin (1.5.1)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5)
tilt (2.0.2, 1.4.1)
treetop (1.4.14)
turbolinks (1.2.0)
twitter-stream (0.1.16)
tzinfo (1.2.2)
tzinfo-data (1.2014.2)
uglifier (2.1.1)
uuidtools (2.1.3)
web-console (2.0.0)
ya2yaml (0.31)
yajl-ruby (1.1.0)
bash-4.1$ bundle list
Gems included by the bundle:
  * actionmailer (4.2.5)
  * actionpack (4.2.5)
  * actionpack-action_caching (1.1.1)
  * actionpack-xml_parser (1.0.2)
  * actionview (4.2.5)
  * activejob (4.2.5)
  * activemodel (4.2.5)
  * activerecord (4.2.5)
  * activesupport (4.2.5)
  * acts-as-taggable-on (3.5.0)
  * addressable (2.4.0)
  * arel (6.0.3)
  * awesome_nested_set (3.0.3)
  * builder (3.2.2)
  * bundler (1.10.4)
  * coderay (1.1.0)
  * concurrent-ruby (1.0.0)
  * css_parser (1.3.7)
  * erubis (2.7.0)
  * globalid (0.3.6)
  * haml (4.0.7)
  * haml-rails (0.9.0)
  * html2haml (2.0.0)
  * htmlentities (4.3.1)
  * i18n (0.7.0)
  * jquery-rails (3.1.4)
  * json (1.8.3)
  * loofah (2.0.3)
  * mail (2.6.3)
  * mime-types (2.99)
  * mini_portile2 (2.0.0)
  * minitest (5.8.3)
  * mysql2 (0.3.14)
  * net-ldap (0.12.1)
  * nokogiri (1.6.7)
  * protected_attributes (1.1.3)
  * rack (1.6.4)
  * rack-openid (1.4.2)
  * rack-test (0.6.3)
  * rails (4.2.5)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-html-sanitizer (1.0.2)
  * railties (4.2.5)
  * rake (10.4.2)
  * rbpdf (1.19.0)
  * rbpdf-font (1.19.0)
  * redcarpet (3.3.3)
  * redmine_acts_as_taggable_on (1.1.0 a939bae)
  * request_store (1.0.5)
  * require_patch (0.2.0)
  * rmagick (2.15.4)
  * roadie (3.1.0)
  * roadie-rails (1.1.0)
  * ruby-openid (2.3.0)
  * ruby_parser (3.7.2)
  * sexp_processor (4.6.0)
  * sprockets (3.5.1)
  * sprockets-rails (2.3.3)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (2.0.2)
  * tzinfo (1.2.2)
  * ya2yaml (0.31)
bash-4.1$ 
```

**Comment by Loriowar** [comment]
Thanks for compatibility issue. I look on this in closest time.
