### ISSUE TITLE
not compatible with scrum plugin

### ISSUE THREAD

**Issue by archonwang** [Loriowar/redmine_issues_tree#40]
@Loriowar , I found it not compatible with scrum plugin, could you fixed it. Thanks.
the scrum plugin: https://redmine.ociotec.com/projects/redmine-plugin-scrum/

my environment is 
```
Environment:
  Redmine version                3.3.0.stable.15819
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

error log
> A NoMethodError occurred in issues_trees#tree_index:
>  
>   undefined method `<<' for {}:Hash
>   plugins/scrum/lib/scrum/issue_query_patch.rb:40:in `issues_with_scrum'
>  
>  
> -------------------------------
> Request:
> -------------------------------
>  
> * URL : http://192.168.1.41/projects/uth_testteam/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=due_date&c%5B%5D=updated_on&c%5B%5D=fixed_version&c%5B%5D=start_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=uth_testteam&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
>   * HTTP Method: GET
>   * IP address : 192.168.60.238
>   * Parameters : {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "due_date", "updated_on", "fixed_version", "start_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"uth_testteam", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""], "controller"=>"issues_trees", "action"=>"tree_index"}
>   * Timestamp  : 2016-09-05 03:32:11 UTC
>   * Server : jira
>   * Rails root : /opt/redmine-3.3
>   * Process: 30422
>  
> -------------------------------
> Session:
> -------------------------------
>  
>   * session id: "6d78f6e25bf633349961315313f7b92f"
>   * data: {"session_id"=>"6d78f6e25bf633349961315313f7b92f",
>    "user_id"=>8,
>    "tk"=>"f57f69f7419af208a5fe484464a73688ee6c3cf4",
>    "sudo_timestamp"=>1473041388,
>    "_csrf_token"=>"eNZEynNjtNO5Vo81cg6tPF0jgigzpUZsezkP1rrhbVQ=",
>    "recent_projects"=>[2, 10],
>    "query"=>
>     {:project_id=>2,
>      :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}},
>      :group_by=>"",
>      :column_names=>
>       [:tracker,
>        :subject,
>        :status,
>        :author,
>        :assigned_to,
>        :priority,
>        :due_date,
>        :updated_on,
>        :fixed_version,
>        :start_date],
>      :totalable_names=>[:estimated_hours, :spent_hours]},
>    "issues_index_sort"=>"id:desc",
>    "issues_trees_tree_index_sort"=>"id:desc"}
>  
> -------------------------------
> Environment:
> -------------------------------
>  
>   * GATEWAY_INTERFACE                              : CGI/1.2
>   * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
>   * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
>   * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8,en;q=0.6
>   * HTTP_CONNECTION                                : keep-alive
>   * HTTP_COOKIE                                    : autologin=df95bc5acf08ba7db8767eb2c92997aaf2089912; _redmine_session=dTA3a3B6LzFUdUJUWGlkV2c4OW1EZ1pESVdZejNSOUpSSXN0T01YMkR1ZEJjV2VtdUV4K2VmWDdWMmlCaGRsUSthQTc3eUcxWGhLU3ZLSEE1OE4yb3U4aFZERms1UzJuS2g2cW96ZzExcE15QnA3UU9yWmphV3NVbFFzTDlzb2JDRlpwK0NEd3FBNDhIUkc1ZXNLVlpINmFEaXVNZWhCQVUycmN1eWUxTFdZWHpibG1Oa2kzd0tUZG9wN0lnQ2tHRXNEa2drUzNBaXdKMGRyTXJTV041Qm1YNkV5UFQ3Z0loUkd5cEhnZUZiWnNRaSsrd08wZFlNVlp6c3lEMjhBdmcyblIxTkRoYUtYaWJEUjJYdkk4UXZsakRFYjI1NkRaNlRmWWpKQ1VZVzIwWit0SWNBcUsrTW9mQlhqNVl0NDJIdGZpTXNMKzBjQjFRK0xXaE1OOUZBTGJQZkdrc3daUmR3Y3I1UzZRR0U5MFhyQmd6ZEFLaGJoR0xibUVNaVFtV1VXeVlkTW8vUHNyRk42MjlBTmY5TEhiUjBGSVFvakNHSURWQTY2V3dTK1JWVjkwd211WDZhYk1uQmtab3dwWVhUQ1lzaFlicHU5NmVjajJRUnpEdHJ2ZEJWQmRwUEJHbHR1WlZab2FDZWtRbTcvQWI5aUdqQVdFdkxOeHhzcEVkSzlvM3lKQmFuTGVUVFRZSVl5Mkt5YjNkbENjZURacVE5cksxNGQ4bEUybjdDbVlwWXpNbEZOY0s1RVZ6T1VYUXZ3ZDVmTFVmR3hHZThpUXdZRWlQbGtncWx1dTNvQnNwbFJZUElpTEZnST0tLVlqbVJndHU5ZkN4cEk1bHJVRjRFSEE9PQ%3D%3D--a8c2fc0f9fda0c92fd07b0258e9742b58c75d73c
>   * HTTP_HOST                                      : 192.168.1.41
> * HTTP_REFERER : http://192.168.1.41/projects/uth_testteam/issues
>   * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
>   * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36
>   * HTTP_VERSION                                   : HTTP/1.1
>   * ORIGINAL_FULLPATH                              : /projects/uth_testteam/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=due_date&c%5B%5D=updated_on&c%5B%5D=fixed_version&c%5B%5D=start_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=uth_testteam&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
>   * ORIGINAL_SCRIPT_NAME                           :
>   * PATH_INFO                                      : /projects/uth_testteam/issues_trees/tree_index
>   * QUERY_STRING                                   : c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=due_date&c%5B%5D=updated_on&c%5B%5D=fixed_version&c%5B%5D=start_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=uth_testteam&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
>   * REMOTE_ADDR                                    : 192.168.60.238
>   * REQUEST_METHOD                                 : GET
>   * REQUEST_PATH                                   : /projects/uth_testteam/issues_trees/tree_index
>   * REQUEST_URI                                    : /projects/uth_testteam/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=due_date&c%5B%5D=updated_on&c%5B%5D=fixed_version&c%5B%5D=start_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=uth_testteam&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
>   * ROUTES_56162520_SCRIPT_NAME                    :
>   * SCRIPT_NAME                                    :
>   * SERVER_NAME                                    : 192.168.1.41
>   * SERVER_PORT                                    : 80
>   * SERVER_PROTOCOL                                : HTTP/1.1
>   * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
>   * action_controller.instance                     : #<IssuesTreesController:0x00000004d0cd58>
>   * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x000000065a4e88>
>   * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00000004cfef78>
>   * action_dispatch.cookies_digest                 :
>   * action_dispatch.cookies_serializer             :
>   * action_dispatch.encrypted_cookie_salt          : encrypted cookie
>   * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
>   * action_dispatch.http_auth_salt                 : http authentication
>   * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x00000004fc0068>
>   * action_dispatch.logger                         : #<ActiveSupport::Logger:0x00000006a424e0>
>   * action_dispatch.parameter_filter               : [:password]
>   * action_dispatch.redirect_filter                : []
>   * action_dispatch.remote_ip                      : 192.168.60.238
>   * action_dispatch.request.content_type           :
>   * action_dispatch.request.formats                : [#<Mime::Type:0x00000003e22a90 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-4223705978519754423>]
>   * action_dispatch.request.parameters             : {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "due_date", "updated_on", "fixed_version", "start_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"uth_testteam", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""], "controller"=>"issues_trees", "action"=>"tree_index"}
>   * action_dispatch.request.path_parameters        : {:controller=>"issues_trees", :action=>"tree_index", :project_id=>"uth_testteam"}
>   * action_dispatch.request.query_parameters       : {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "due_date", "updated_on", "fixed_version", "start_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"uth_testteam", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""]}
>   * action_dispatch.request.request_parameters     : {}
>   * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"6d78f6e25bf633349961315313f7b92f", "user_id"=>8, "tk"=>"f57f69f7419af208a5fe484464a73688ee6c3cf4", "sudo_timestamp"=>1473041388, "_csrf_token"=>"eNZEynNjtNO5Vo81cg6tPF0jgigzpUZsezkP1rrhbVQ=", "recent_projects"=>[2, 10], "query"=>{:project_id=>2, :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}}, :group_by=>nil, :column_names=>nil, :totalable_names=>[:estimated_hours, :spent_hours]}, "issues_index_sort"=>"id:desc"}
>   * action_dispatch.request_id                     : 89443f7a-7a54-486d-9ed1-956e0b46dd82
>   * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000006b1f1b0>
>   * action_dispatch.secret_key_base                : 59dda17a42803617f96151518b9aeecb94e132c6f140123f1982e1c8ae15d0103ffa854c4d8b0019
>   * action_dispatch.secret_token                   :
>   * action_dispatch.show_detailed_exceptions       : false
>   * action_dispatch.show_exceptions                : true
>   * action_dispatch.signed_cookie_salt             : signed cookie
>   * async.callback                                 : #<Method: Thin::Connection#post_process>
>   * async.close                                    : #<EventMachine::DefaultDeferrable:0x00000004de1670>
>   * rack.errors                                    : #<IO:0x0000000244d598>
>   * rack.input                                     : #<StringIO:0x00000004de3998>
>   * rack.multiprocess                              : false
>   * rack.multithread                               : true
>   * rack.request.cookie_hash                       : {"autologin"=>"df95bc5acf08ba7db8767eb2c92997aaf2089912", "_redmine_session"=>"dTA3a3B6LzFUdUJUWGlkV2c4OW1EZ1pESVdZejNSOUpSSXN0T01YMkR1ZEJjV2VtdUV4K2VmWDdWMmlCaGRsUSthQTc3eUcxWGhLU3ZLSEE1OE4yb3U4aFZERms1UzJuS2g2cW96ZzExcE15QnA3UU9yWmphV3NVbFFzTDlzb2JDRlpwK0NEd3FBNDhIUkc1ZXNLVlpINmFEaXVNZWhCQVUycmN1eWUxTFdZWHpibG1Oa2kzd0tUZG9wN0lnQ2tHRXNEa2drUzNBaXdKMGRyTXJTV041Qm1YNkV5UFQ3Z0loUkd5cEhnZUZiWnNRaSsrd08wZFlNVlp6c3lEMjhBdmcyblIxTkRoYUtYaWJEUjJYdkk4UXZsakRFYjI1NkRaNlRmWWpKQ1VZVzIwWit0SWNBcUsrTW9mQlhqNVl0NDJIdGZpTXNMKzBjQjFRK0xXaE1OOUZBTGJQZkdrc3daUmR3Y3I1UzZRR0U5MFhyQmd6ZEFLaGJoR0xibUVNaVFtV1VXeVlkTW8vUHNyRk42MjlBTmY5TEhiUjBGSVFvakNHSURWQTY2V3dTK1JWVjkwd211WDZhYk1uQmtab3dwWVhUQ1lzaFlicHU5NmVjajJRUnpEdHJ2ZEJWQmRwUEJHbHR1WlZab2FDZWtRbTcvQWI5aUdqQVdFdkxOeHhzcEVkSzlvM3lKQmFuTGVUVFRZSVl5Mkt5YjNkbENjZURacVE5cksxNGQ4bEUybjdDbVlwWXpNbEZOY0s1RVZ6T1VYUXZ3ZDVmTFVmR3hHZThpUXdZRWlQbGtncWx1dTNvQnNwbFJZUElpTEZnST0tLVlqbVJndHU5ZkN4cEk1bHJVRjRFSEE9PQ==--a8c2fc0f9fda0c92fd07b0258e9742b58c75d73c"}
>   * rack.request.cookie_string                     : autologin=df95bc5acf08ba7db8767eb2c92997aaf2089912; _redmine_session=dTA3a3B6LzFUdUJUWGlkV2c4OW1EZ1pESVdZejNSOUpSSXN0T01YMkR1ZEJjV2VtdUV4K2VmWDdWMmlCaGRsUSthQTc3eUcxWGhLU3ZLSEE1OE4yb3U4aFZERms1UzJuS2g2cW96ZzExcE15QnA3UU9yWmphV3NVbFFzTDlzb2JDRlpwK0NEd3FBNDhIUkc1ZXNLVlpINmFEaXVNZWhCQVUycmN1eWUxTFdZWHpibG1Oa2kzd0tUZG9wN0lnQ2tHRXNEa2drUzNBaXdKMGRyTXJTV041Qm1YNkV5UFQ3Z0loUkd5cEhnZUZiWnNRaSsrd08wZFlNVlp6c3lEMjhBdmcyblIxTkRoYUtYaWJEUjJYdkk4UXZsakRFYjI1NkRaNlRmWWpKQ1VZVzIwWit0SWNBcUsrTW9mQlhqNVl0NDJIdGZpTXNMKzBjQjFRK0xXaE1OOUZBTGJQZkdrc3daUmR3Y3I1UzZRR0U5MFhyQmd6ZEFLaGJoR0xibUVNaVFtV1VXeVlkTW8vUHNyRk42MjlBTmY5TEhiUjBGSVFvakNHSURWQTY2V3dTK1JWVjkwd211WDZhYk1uQmtab3dwWVhUQ1lzaFlicHU5NmVjajJRUnpEdHJ2ZEJWQmRwUEJHbHR1WlZab2FDZWtRbTcvQWI5aUdqQVdFdkxOeHhzcEVkSzlvM3lKQmFuTGVUVFRZSVl5Mkt5YjNkbENjZURacVE5cksxNGQ4bEUybjdDbVlwWXpNbEZOY0s1RVZ6T1VYUXZ3ZDVmTFVmR3hHZThpUXdZRWlQbGtncWx1dTNvQnNwbFJZUElpTEZnST0tLVlqbVJndHU5ZkN4cEk1bHJVRjRFSEE9PQ%3D%3D--a8c2fc0f9fda0c92fd07b0258e9742b58c75d73c
>   * rack.request.query_hash                        : {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "due_date", "updated_on", "fixed_version", "start_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"uth_testteam", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""]}
>   * rack.request.query_string                      : c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=due_date&c%5B%5D=updated_on&c%5B%5D=fixed_version&c%5B%5D=start_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=uth_testteam&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
>   * rack.run_once                                  : false
>   * rack.session                                   : #<ActionDispatch::Request::Session:0x00000004d9dbf0>
>   * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00000004d9db00>
>   * rack.url_scheme                                : http
>   * rack.version                                   : [1, 0]
>  
> -------------------------------
> Backtrace:
> -------------------------------
>  
>   plugins/scrum/lib/scrum/issue_query_patch.rb:40:in `issues_with_scrum'
>   plugins/redmine_issues_tree/app/controllers/issues_trees_controller.rb:35:in `tree_index'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by Loriowar** [comment]
This is old issue (look at  #15). I described all known incompatible plugins on [Redmine page of this plugin](https://www.redmine.org/plugins/redmine_issues_tree/). if it is not noticeable I can duplicate this information in Readme.

**Comment by archonwang** [comment]
@Loriowar ,
OK. thanks

**Comment by ace280** [comment]
Is this incompatibility still valid for 4.1.x versions?

**Comment by ace280** [comment]
If there is no news on this, however, maybe this issue can be closed?
