### ISSUE TITLE
ActionView::Template::Error (undefined method `allowed_target_trackers' 

### ISSUE THREAD

**Issue by Vitexus** [Loriowar/redmine_issues_tree#41]
Hallo,
i have problem with your current plugin version from git on my 

```
Environment:
  Redmine version                3.2.3.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  advanced_roadmap               0.10.1
  redmine_agile                  1.4.1
  redmine_bootstrap_kit          0.2.4
  redmine_dmsf                   1.5.6
  redmine_emojibutton            0.4.1
  redmine_git_hosting            1.2.1
  redmine_issue_completion       0.0.2
  redmine_issues_tree            0.0.1
  time_logger                    0.5.3
```

it caused

```
Started GET "/redmine/projects/flexihubee/issues" for 10.11.23.85 at 2016-09-05 10:53:06 +0200
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"flexihubee"}
  Current user: vitex (id=3)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_issues_index_header_tags.html.haml (2.2ms)
  Rendered plugins/redmine_issues_tree/app/views/issues/index.html.erb within layouts/base (8.3ms)
Completed 500 Internal Server Error in 203ms (ActiveRecord: 72.7ms)

ActionView::Template::Error (undefined method `allowed_target_trackers' for #<Class:0x00000004c98250>):
    3: <%# end patch %>
    4: 
    5: <div class="contextual">
    6:   <% if User.current.allowed_to?(:add_issues, @project, :global => true) && (@project.nil? || Issue.allowed_target_trackers(@project).any?) %>
    7:     <%= link_to l(:label_issue_new), _new_project_issue_path(@project), :class => 'icon icon-add new-issue' %>
    8:   <% end %>
    9: 
  plugins/redmine_issues_tree/app/views/issues/index.html.erb:6:in `_plugins_redmine_issues_tree_app_views_issues_index_html_erb___2015112121489083949_55336000'
  plugins/advanced_roadmap/lib/advanced_roadmap/issues_controller_patch.rb:28:in `render'
  app/controllers/issues_controller.rb:77:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:76:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
```

but  older version ( i use one from 2015 ) works well.

Thank you for your time

**Comment by Vitexus** [comment]
Ah! Sorry  i use one of https://www.redmine.org/plugins/a_common_libs - twitter bootstrap...

**Comment by gargtushar** [comment]
already installed this plugin but getting the same  error

**Comment by Loriowar** [comment]
"This plugin" which plugin exactly? Redmine_issues_tree incompatible with a_commin_libs. So, you must select only one of them.

**Comment by nyobakaronjajal** [comment]
i do not install a_commin_libs, but still getting the same error..
Please help me. Thank you.

**Comment by Loriowar** [comment]
@nyobakaronjajal if you have a problem, please, create a new issue, provide a full backtrace, description of environment and list of installed plugins.
Most likely, you have one of incompatible plugins in your installation. That's all what I can say based on your comment.

**Comment by nyobakaronjajal** [comment]
@Loriowar i know what i miss.. i use the branch master for redmine version 3.2 .. Then when i choose branch for 3.2 it's working fine..
Thank you.
