### ISSUE TITLE
open issues page occured 500 error

### ISSUE THREAD

**Issue by archonwang** [Loriowar/redmine_issues_tree#54]
error log as follows, it seems that conflict with plus_gantt (https://github.com/luciof55/plus_gantt)

```
Started GET "/issue_badge/issues_count" for 192.168.60.252 at 2017-05-31 12:58:14 +0800
Processing by IssueBadgeController#issues_count as JSON
  Current user: pengcheng.hao (id=29)
Started GET "/issues" for 192.168.20.231 at 2017-05-31 12:58:14 +0800
Processing by IssuesController#index as HTML
  Rendered text template (0.0ms)
Completed 200 OK in 70ms (Views: 1.0ms | ActiveRecord: 11.7ms)
  Current user: hui.wang (id=8)
Started GET "/issue_badge/issues_count" for 192.168.50.250 at 2017-05-31 12:58:15 +0800
Processing by IssueBadgeController#issues_count as JSON
  Current user: bin.bai (id=101)
  Rendered text template (0.0ms)
Completed 200 OK in 74ms (Views: 0.5ms | ActiveRecord: 44.6ms)
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_issues_index_header_tags.html.haml (1.2ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_tree_view.html.haml (0.7ms)
Read fragment views/queries/filter/user-8/2017-04-20T06:45:51Z/2017-05-16 09:48:24 UTC/e42c5980be4ccd0f7205b2df55f850cf (0.4ms)
  Rendered plugins/redmine_performance/app/views/queries/_filters.html.erb (9.4ms)
  Rendered queries/_columns.html.erb (4.2ms)
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_issues_tree_view/app/views/issues/_list.html.erb (410.9ms)
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_view_issues_index_bottom.erb (4.9ms)
  Rendered plugins/plus_gantt/app/views/plusgantt/_issues_sidebar.html.erb (31.8ms)
  Rendered issues/_sidebar.html.erb (34.0ms)
  Rendered plugins/redmine_issues_tree/app/views/issues/index.html.erb within layouts/base (508.0ms)
Completed 500 Internal Server Error in 3389ms (ActiveRecord: 1384.3ms)

ActionView::Template::Error (No route matches {:action=>"show", :controller=>"plusgantt_dashboard", :project_id=>nil}):
    1: <% if User.current.allowed_to?(:view_plusgantt, @project, :global => true) %>
    2: <h3><%= l(:label_plusgantt) %></h3>
    3: <%= '&nbsp;&nbsp;'.html_safe %>
    4: <%= link_to l(:label_pg_dashboard), {:controller => "plusgantt_dashboard", :action => "show", :project_id => @project} %><br>
    5: <%= '&nbsp;&nbsp;'.html_safe %>
    6: <%= link_to l(:label_plusgantt_chart), {:controller => "plusgantt", :action => "show", :project_id => @project} %><br>
    7: <% end %>
  plugins/plus_gantt/app/views/plusgantt/_issues_sidebar.html.erb:4:in `_2b6b4f500c0d2ca938b3a3585f6b163f'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_sidebar.html.erb:21:in `_9882d6039c6e761b99504be4b08b0846'
  plugins/redmine_issues_tree/app/views/issues/index.html.erb:120:in `block in _edac2f32add2e363a8a89ba12b8edbeb'
  plugins/redmine_issues_tree/app/views/issues/index.html.erb:119:in `_edac2f32add2e363a8a89ba12b8edbeb'
  plugins/redmine_issues_tree_view/lib/issues_tree_view_issues_controller_patch.rb:53:in `block (2 levels) in index'
  plugins/redmine_issues_tree_view/lib/issues_tree_view_issues_controller_patch.rb:52:in `index'
  plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/issues_controller_patch.rb:17:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/issues" for 192.168.20.231 at 2017-05-31 12:58:18 +0800
Processing by IssuesController#index as */*
  Current user: hui.wang (id=8)
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_issues_index_header_tags.html.haml (0.9ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_tree_view.html.haml (0.3ms)
Read fragment views/queries/filter/user-8/2017-04-20T06:45:51Z/2017-05-16 09:48:24 UTC/e42c5980be4ccd0f7205b2df55f850cf (0.2ms)
  Rendered plugins/redmine_performance/app/views/queries/_filters.html.erb (7.5ms)
  Rendered queries/_columns.html.erb (3.9ms)
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_issues_tree_view/app/views/issues/_list.html.erb (331.6ms)
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_view_issues_index_bottom.erb (4.1ms)
  Rendered plugins/plus_gantt/app/views/plusgantt/_issues_sidebar.html.erb (31.3ms)
  Rendered issues/_sidebar.html.erb (33.0ms)
  Rendered plugins/redmine_issues_tree/app/views/issues/index.html.erb (421.7ms)
Completed 500 Internal Server Error in 3573ms (ActiveRecord: 1389.8ms)

ActionView::Template::Error (No route matches {:action=>"show", :controller=>"plusgantt_dashboard", :project_id=>nil}):
    1: <% if User.current.allowed_to?(:view_plusgantt, @project, :global => true) %>
    2: <h3><%= l(:label_plusgantt) %></h3>
    3: <%= '&nbsp;&nbsp;'.html_safe %>
    4: <%= link_to l(:label_pg_dashboard), {:controller => "plusgantt_dashboard", :action => "show", :project_id => @project} %><br>
    5: <%= '&nbsp;&nbsp;'.html_safe %>
    6: <%= link_to l(:label_plusgantt_chart), {:controller => "plusgantt", :action => "show", :project_id => @project} %><br>
    7: <% end %>
  plugins/plus_gantt/app/views/plusgantt/_issues_sidebar.html.erb:4:in `_2b6b4f500c0d2ca938b3a3585f6b163f'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_sidebar.html.erb:21:in `_9882d6039c6e761b99504be4b08b0846'
  plugins/redmine_issues_tree/app/views/issues/index.html.erb:120:in `block in _edac2f32add2e363a8a89ba12b8edbeb'
  plugins/redmine_issues_tree/app/views/issues/index.html.erb:119:in `_edac2f32add2e363a8a89ba12b8edbeb'
  plugins/redmine_issues_tree_view/lib/issues_tree_view_issues_controller_patch.rb:53:in `block (2 levels) in index'
  plugins/redmine_issues_tree_view/lib/issues_tree_view_issues_controller_patch.rb:52:in `index'
  plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/issues_controller_patch.rb:17:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by rvcoutinho** [comment]
+1

**Comment by adrianobr** [comment]
+1

**Comment by Nickj1** [comment]
+1
