### ISSUE TITLE
conflicts and crashes with redmineup_tag plugin

### ISSUE THREAD

**Issue by mchengh** [Loriowar/redmine_issues_tree#67]
Sir, 
Thank you for the plugin.

When try to use the redmineup_tag plugin, from https://www.redmine.org/plugins/redmineup_tags ( need to provide an email address to get the download link, v2.0.1 by current) , and installed the redmine_issues_tree 3.3.x branch.
Both plugins could be installed successfully, when used, and click the "tree_view" button, the page crashes.

Error msg shows 

`Redmine. Error 500
Global error
undefined local variable or method `sidebar_tags' for #<#<Class:0x007fb451becf50>:0x007fb451bf42a0>
?

Error log

        /opt/bitnami/apps/redmine/htdocs/plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb:1:in `_575794c4486121b4ce95f09003f34b52'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/deface-1.2.0/lib/deface/action_view_extensions.rb:41:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:25:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers/action_view_mods.rb:14:in `render'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook/view_listener.rb:57:in `map'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook/view_listener.rb:57:in `block in render_on'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook.rb:61:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook.rb:61:in `block in call_hook'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook.rb:58:in `tap'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook.rb:58:in `call_hook'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/hook.rb:96:in `call_hook'
/opt/bitnami/apps/redmine/htdocs/app/views/issues/_sidebar.html.erb:22:in `_24723fc54cd5319a35108587093d3059'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/deface-1.2.0/lib/deface/action_view_extensions.rb:41:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:25:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers/action_view_mods.rb:12:in `block in render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers.rb:92:in `non_haml'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers/action_view_mods.rb:12:in `render'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml:81:in `block in _971c7356648a38fee5071c953b4a3c95'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers.rb:382:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers.rb:382:in `block in capture_haml'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers.rb:667:in `with_haml_buffer'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers.rb:378:in `capture_haml'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers/xss_mods.rb:62:in `capture_haml_with_haml_xss'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/haml-5.0.1/lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/helpers/capture_helper.rb:152:in `content_for'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml:80:in `_971c7356648a38fee5071c953b4a3c95'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/deface-1.2.0/lib/deface/action_view_extensions.rb:41:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:46:in `render_template'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:27:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:100:in `_render_template'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:83:in `render_to_body'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/abstract_controller/rendering.rb:25:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:16:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/opt/bitnami/ruby/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:313:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:312:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:312:in `block in halting'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
 

`

ENV

System info: 	Linux ubuntu 3.13.0-110-generic #157-Ubuntu SMP Mon Feb 20 11:54:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.1.10-p492 (2016-04-01) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Cvs                            1.12.13
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  _query                         0.0.2
  a_common_libs                  2.3.5
  advanced_roadmap               0.11.0
  clipboard_image_paste          1.12
  issue_id                       0.0.2
  mega_calendar                  1.6.0
  periodictask                   3.2.0
  projects_show                  0.0.3
  quick_view                     0.3.0
  redmine_agile                  1.4.2
  redmine_checklists             3.1.6
  redmine_code_review            0.8.0
  redmine_custom_workflows       0.1.5
  redmine_dmsf                   1.5.9
  redmine_drawio                 0.5.0
  redmine_favorite_projects      2.0.3
  redmine_image_clipboard_paste  3.3.0
  redmine_include_macro_extension 0.0.3
  redmine_issue_tabs             1.2.3
  redmine_issue_templates        0.1.6
  redmine_issues_tree            0.0.11
  redmine_ldap_sync              2.0.7
  redmine_lightbox2              0.3.2
  redmine_my_roadmaps            0.2.1_redmine3.0
  redmine_questions              0.0.7
  redmine_subtask_list_accordion 1.3.2
  redmine_tweaks                 0.5.8
  redmine_wiki_extensions        0.7.0
  redmine_work_time              0.3.4
  redmine_xlsx_format_issue_exporter 0.1.3
  redmine_zenedit                0.0.2
  redmineup_tags                 2.0.1
  sidebar_hide                   0.0.8
  usability                      2.2.6
  wiking                         1.1.0

**Comment by mchengh** [comment]
The issue also discussed in #68 , and close this one.
