### ISSUE TITLE
sidebar_tags?

### ISSUE THREAD

**Issue by gisok** [Loriowar/redmine_issues_tree#68]
Redmine. Error 500
Global error
undefined local variable or method `sidebar_tags' for #<#<Class:0x00007f45474c2320>:0x00007f45474b9220> Did you mean? sidebar_queries

**Comment by Loriowar** [comment]
@gisok I can't help without details about installation. Please, specify version of Redmine, version of all installed plugins, specify branch of `redmine_issues_tree`, name and version of OS and so on. Additionally, please, carefully read a `ReadMe` file. There is some important instructions about plugin installation.

**Comment by gisok** [comment]
# Redmine. Error 500

Global error
undefined local variable or method `sidebar_tags' for #<#<Class:0x00007f12ea7d41b0>:0x00007f12c8142418> Did you mean? sidebar_queries



# Error log

        /usr/local/redmine-3.4.3/plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb:1:in `_plugins_redmineup_tags_app_views_issues__tags_sidebar_html_erb___3761162809262589771_69859689915880'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:25:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:14:in `render'
/usr/local/redmine-3.4.3/lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
/usr/local/redmine-3.4.3/lib/redmine/hook/view_listener.rb:57:in `map'
/usr/local/redmine-3.4.3/lib/redmine/hook/view_listener.rb:57:in `block in render_on'
/usr/local/redmine-3.4.3/lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
/usr/local/redmine-3.4.3/lib/redmine/hook.rb:61:in `each'
/usr/local/redmine-3.4.3/lib/redmine/hook.rb:61:in `block in call_hook'
/usr/local/redmine-3.4.3/lib/redmine/hook.rb:58:in `tap'
/usr/local/redmine-3.4.3/lib/redmine/hook.rb:58:in `call_hook'
/usr/local/redmine-3.4.3/lib/redmine/hook.rb:96:in `call_hook'
/usr/local/redmine-3.4.3/app/views/issues/_sidebar.html.erb:15:in `_app_views_issues__sidebar_html_erb___2368547359240335757_69859615165580'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:25:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:12:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers.rb:92:in `non_haml'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:12:in `render'
/usr/local/redmine-3.4.3/plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml:80:in `block in _plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_haml__3260942127309383424_69859609962600'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers.rb:382:in `block in capture_haml'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers.rb:667:in `with_haml_buffer'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers.rb:378:in `capture_haml'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers/xss_mods.rb:62:in `capture_haml_with_haml_xss'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:152:in `content_for'
/usr/local/redmine-3.4.3/plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml:79:in `_plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_haml__3260942127309383424_69859609962600'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:14:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/usr/local/redmine-3.4.3/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/lock.rb:17:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
/root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
      
# Environment:


  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL

**Comment by Loriowar** [comment]
Looks like `redmine_issues_tree` is incompatible with `redmineup_tags` plugin. On [redmineup_tags](http://www.redmine.org/plugins/redmine_tags) page specified support of `2.x` Redmine versions. So, I don't know exact reason of incompatibility. Hence, you can investigate problem by yourself and create a pull request or wait until I make same thing. There is no time estimation in the second case.

**Comment by mchengh** [comment]
According to the description, redmineup_tags supports 3.4.x, 3.3.x, and do works on 3.3.x as used.
Thanks.

https://www.redmine.org/plugins/redmineup_tags
Author: | Kirill Bezrukov (RedmineUP)
-- | --
https://www.redmineup.com/pages/plugins/tags
-
2017-07-26 (6 months ago)
2.0.1
Redmine 3.4.x, 3.3.x, 3.2.x, 3.1.x, 3.0.x, 2.6.x, 2.5.x, 2.4.x, 2.3.x

**Comment by seza2783** [comment]
Same problem.

**Comment by seza2783** [comment]
Found work around.
It works as expected in regular issue list view, but you won't have sidebar with tags filters in issue tree view. But it is better then nothing :)

Patch:
../redmineup_tags/app/views/issues/_tags_sidebar.html.erb
Add `defined?(sidebar_tags) &&`  in 1 line.
It should look like this:
`<% defined?(sidebar_tags) && unless sidebar_tags.empty? -%>`

**Comment by cyboman32** [comment]
Same problem here

BTW
redmine_tags now supports 3.x and works very well:


_Changelog
3.2.2 (2018-01-24)
Compatible with Redmine 3.4.x, 3.3.x, 3.2.x, 3.1.x._

So seems this still need to be fixed...
