### ISSUE TITLE
3.4.x version with tr.yml error

### ISSUE THREAD

**Issue by albenstein** [Loriowar/redmine_issues_tree#72]
Hi,
We're using redmine_issues_tree plugin with redmine 3.3 version. We're now updating to redmine 3.4 version and change plugin's branch to 3.4.x but there is some errors in locale file.

```
[2018-03-28 15:59:35.140 +0300] (18365) FATAL
ActionView::Template::Error (can not load translations from /opt/redmine/plugins/redmine_issues_tree/config/locales/tr.yml: #<Psych::SyntaxError: (/opt/redmine/plugins/redmine_issues_tree/config/locales/tr.yml): did not find expected key while parsing a block mapping at line 10 column 7>):
    1: <h2><%= l(:label_home) %></h2>
    2:
    3: <div class="splitcontentleft">
    4:   <div class="wiki">
  lib/redmine/i18n.rb:185:in `init_translations'
  lib/redmine/i18n.rb:199:in `lookup'
  lib/redmine/i18n.rb:27:in `l'
  app/views/welcome/index.html.erb:1:in `_app_views_welcome_index_html_erb___2036973335937073890_35194500'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by Loriowar** [comment]
Fixed in 966ea96fe8c3bebf0662c085c8e3f8cb6bf775ff. Fix added to all `3.x` branches.
