### ISSUE TITLE
Cannot install this plugin

### ISSUE THREAD

**Issue by iamfangk** [Loriowar/redmine_issues_tree#74]
Copy Folder: C:\Bitnami\redmine-3.4.4-2\apps\redmine\htdocs\plugins\redmine_issues_tree

CMD: bundle exec rake redmine:plugins:migrate RAILS_ENV=production

Error Message:
   (in C:/Bitnami/redmine-3.4.4-2/apps/redmine/htdocs)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `require_patch' for #<ActionDispatch::Reloader:0x898c3c8>
C:/Bitnami/redmine-3.4.4-2/apps/redmine/htdocs/plugins/redmine_issues_tree/init.rb:17:in `block in <top (required)>'
C:/Bitnami/redmine-3.4.4-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
C:/Bitnami/redmine-3.4.4-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
C:/Bitnami/redmine-3.4.4-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
C:/Bitnami/redmine-3.4.4-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'

**Comment by Loriowar** [comment]
This plugin has no migrations, but has gem dependencies. So, looks like you forget to run `bundle install`. Run it in corresponding environment, restart your app and test again.

**Comment by iamfangk** [comment]
Thanks a lot. Now the plugin is working well.
