### ISSUE TITLE
Error in Redmine 4.0.5

### ISSUE THREAD

**Issue by amlinux** [Loriowar/redmine_issues_tree#99]
When I open the list of issues I see a 500 error and the following in the log:

```
I, [2019-11-05T15:55:53.398543 #1]  INFO -- : Started GET "/projects/xxxxx/issues" for 10.101.2.76 at 2019-11-05 15:55:53 +0000
I, [2019-11-05T15:55:53.400472 #1]  INFO -- : Processing by IssuesController#index as HTML
I, [2019-11-05T15:55:53.400554 #1]  INFO -- :   Parameters: {"project_id"=>"xxxxx"}
I, [2019-11-05T15:55:53.518943 #1]  INFO -- :   Current user: xxxxx (id=1)
I, [2019-11-05T15:55:53.536412 #1]  INFO -- : Completed 500 Internal Server Error in 136ms (ActiveRecord: 14.9ms)
F, [2019-11-05T15:55:53.537428 #1] FATAL -- :
F, [2019-11-05T15:55:53.537522 #1] FATAL -- : NoMethodError (undefined method `with_indifferent_access' for #<ActionController::Parameters:0x00005630c2d1a508>):
F, [2019-11-05T15:55:53.537550 #1] FATAL -- :
F, [2019-11-05T15:55:53.537576 #1] FATAL -- : plugins/redmine_issues_tree/lib/redmine_issues_tree/issues_controller_patch.rb:7:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Redmine: 4.0.5
Issues tree from branch 4.0.x

**Comment by Loriowar** [comment]
@amlinux fixed for `4.0.x` branch in cb249730be40c7c7ed7c2fadd3906387dda0f31c . Please, fetch the latest version of the plugin for your installation, restart web-server and try again.
